when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker buildx create --use
      - docker buildx build --platform linux/amd64 -t ourapp:latest .
