when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker:dind
    commands:
      - docker buildx create --use
      - docker buildx build --load --platform linux/amd64 -t ourapp:latest .
