steps:
  build:
    image: woodpeckerci/plugin-node-pm
    settings:
      pm: npm
      cmd:
        - npm install
        - npm test
        - npm run start
    when:
      event:
        - push
        - pull_request
