steps:
  build:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker buildx create --use
      - docker buildx build --load -t mi-app-node:latest .

  deploy:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run -d -p 5302:5302 mi-app-node:latest
