steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: mi-app-node
      tags: latest
      platforms:
        - linux/amd64
      dockerfile: Dockerfile

  deploy:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run -d -p 5302:5302 mi-app-node:latest
