steps:
  build:
    image: node:14
    commands:
      - npm install
      - npm start &
      - sleep 10
      - curl http://localhost:5302
    when:
      event:
        - push
        - pull_request
