steps:
  build:
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: run index.js # script name
      with: node # if `with` is set, enforce to use this package manager
      frozen_lockfile: true # recommended
      ignore_node_modules: true # recommended
