steps:
  build:
    image: node:14
    commands:
      - npm install
      - npm start &
      - sleep 10
      - curl http://localhost:5302

  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t myapp:latest .
      - docker run -d -p 5302:5302 myapp:latest
    when:
      event:
        - push
        - pull_request

    when:
      event:
        - push
        - pull_request


