pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t sampleapp:v1 .

  # deploy:
  #   image: docker/compose:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   commands:
  #     - docker-compose down --remove-orphans
  #     - docker-compose up -d
