steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      repo: mi-app-node
      tags: latest
      platforms:
        - linux/amd64
      load: true

  deploy:
    image: docker/compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose down --remove-orphans
      - docker-compose up -d
