when:
  - event: push
    branch: main

steps:
  - name: build-docker-imagen
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker buildx create --use
      - docker buildx build --load --platform linux/amd64 -t ourapp:latest .

  - name: deploy-docker-container
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose up -d
