when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker buildx build --load --platform linux/amd64 -t ourapp:latest .
      - docker buildx prune -f

  # - name: deploy
  #   image: docker
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   commands:
  #     - docker-compose up -d
